spring:

  application:
    name: stock
    instance: 1

  kafka:
    consumer:
      group-id: stock-${random.uuid}
      auto-offset-reset: earliest
    bootstrap-servers: 10.101.6.203:9092

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

opentracing:
  jaeger:
    http-sender:
      url: http://jaegertracing:5778/api/traces