spring:

  application:
    name: stock

  datasource:
      url: jdbc:postgresql://localhost:5432/catalogue
      username: catalogue
      password: catalogue

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          # Fix for Spring 2 and Postgres
          lob:
            non_contextual_creation: true
  kafka:
    consumer:
      group-id: stock-${random.uuid}
      auto-offset-reset: earliest

server:
  port: 8081

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true

